name       : python-pyhamcrest
version    : 2.0.2
release    : 5
source     :
    - https://github.com/hamcrest/PyHamcrest/archive/V2.0.2.tar.gz : d5f589020ecb100c2623189a2934750e207ef324688fc4db4261cec007e740ab
homepage   : http://hamcrest.org/
license    : BSD-2-Clause
component  : programming.python
summary    : Hamcrest matchers for Python
description: |
    PyHamcrest is a framework for writing matcher objects, allowing you to declaratively define "match" rules. There are a number of situations where matchers are invaluable, such as UI validation, or data filtering, but it is in the area of writing flexible tests that matchers are most commonly used. This tutorial shows you how to use PyHamcrest for unit testing.
builddeps  :
    - numpy
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
